export enum Channels{FORGET_PASSWORD="FORGET-PASSWORD", RESET_PASSWORD="RESET-PASSWORD", CUSTOM_MAIL= "CUSTOM_MAIL"}

export enum Clients{AUTH="AUTH", NOTIFICATION="NOTIFICATION", BOOKING="BOOKING", FLIGHT="FLIGHT"}

export enum Templates{FORGET_PASSWORD="forget-password", RESET_PASSWORD="reset-password"}