
export enum FlightStatus{UPCOMING="UPCOMING", ONGOING="ONGOING", PAST="PAST", CANCELLED="CANCELLED"}

export enum Channels {AUTHORIZE="AUTHORIZE", AUTHRES="AUTHRES", GETFLIGHTS="GETFLIGHTS", FLIGHTS="FLIGHTS", GETFLIGHT="GETFLIGHT", GETFLIGHTRES="GETFLIGHTRES", NEWBOOKING="NEWBOOKING", CUSTOM_MAIL= "CUSTOM_MAIL"}

export enum Roles{BASIC="BASIC", ADMIN="ADMIN", SUPERADMIN="SUPERADMIN"}