export enum Roles{BASIC="BASIC", ADMIN="ADMIN", SUPERADMIN="SUPERADMIN"}

export enum Channels{FORGET_PASSWORD="FORGET-PASSWORD", RESET_PASSWORD="RESET-PASSWORD", AUTHORIZE="AUTHORIZE", AUTHRES="AUTHRES"}